doc: 'This is the main config file where the processing starts from'

resources:
  var1:
    type: 'normal'
    value:
      dev: 'var1'
      stage: 'var1'
      uat: 'var1'
      production: 'var1'
      qa: 'var1'

  var2:
    type: 'common'
    value: var2

  nested1:
    type: 'nested'
    path: 'templates/nested1.yaml'

  celery:
    type: 'script'
    variable_list: ['a', 'b', 'c']
    path: 'templates/celery.py'
